### ISSUE TITLE
Can’t install using ALTSTORE

### ISSUE THREAD

**Issue by Stephencarew** [EhPanda-Team/EhPanda#250] opened 2022-05-10 20:09 UTC
![Uploading F3E7FEAA-D7EC-41C2-AF01-F94749224FE6.jpeg…]()

when attempting to install, run into this error 
iOS 15.4.1
iPhone XS MAX

**Comment by Stephencarew** [comment] 2022-05-11 11:22
An error occured while installing the app.
Application is missing the application-identifier entitlement

**Comment by tatsuz0u** [comment] 2022-10-02 14:07
There are some changes in v2.4.1 deploy procedure might cause some of those installation failures. But there are also some reports that v2.4.1 can be installed without any error alert popping up. I'll suggest that maybe you can try it with different iOS and AltStore versions, even different Apple IDs.

Since I've installed it successfully on my alternative device that is not on any Apple developer whitelist or something like that. I don't really want to deal with installation issues anymore without reproducible steps. So I'm going to request to close this issue soon, but you can reopen it if you found something interesting or continue in the `Discussions` tab.

**Comment by tatsuz0u** [comment] 2022-10-02 14:07
@chihchy please close this issue if no response from issuer in 1d.

**Closed** 2022-10-02 14:09 UTC
